import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Heart, Menu, X, ShieldCheck, PackageCheck, ChevronDown } from 'lucide-react';
import './styles.css';

const products = [
  ['Forever Close Pendant','Memorial Keepsake','From £89','https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=85'],
  ['Always With Me Ring','Memorial Keepsake','From £109','https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85'],
  ['Little Moments Pendant','Motherhood Keepsake','From £95','https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1200&q=85'],
  ['Forever Pawprint','Pet Memorial','From £89','https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85']
];
const faqs = [
 ['How much material do I need to send?','Only a very small amount is needed. Exact requirements depend on the keepsake you choose.'],
 ['How do you handle sentimental materials?','Every order is handled privately and respectfully. Your materials are treated as precious throughout the making process.'],
 ['How long does my keepsake take?','Turnaround varies by design and current order volume. The exact timeframe is confirmed before your order is made.'],
 ['Can I create something completely custom?','Yes. Custom keepsakes are welcome. Tell us what you would like to preserve and we can discuss the best design.']
];

function App(){
 const [open,setOpen]=useState(null); const [menu,setMenu]=useState(false);
 return <div className="site">
  <div className="announcement">Handcrafted keepsakes made from what matters most <span>·</span> Custom orders welcome</div>
  <header><a className="logo" href="#top"><span>HEARTS</span><b>remembered</b><small>BY M</small></a><nav className={menu?'open':''}>{[['Keepsakes','#keepsakes'],['How It Works','#process'],['Our Story','#story'],['FAQ','#faq']].map(([x,y])=><a key={x} href={y} onClick={()=>setMenu(false)}>{x}</a>)}<a className="navcta" href="#contact">Create Your Keepsake <ArrowRight size={16}/></a></nav><button className="menubtn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  <section id="top" className="hero"><div className="heroCopy"><p className="eyebrow">MEMORIES, MADE TANGIBLE</p><h1>Keep what matters most, <i>close to your heart.</i></h1><p className="lead">Handcrafted keepsake jewellery created with the memories, people and moments you never want to let go of.</p><div className="actions"><a className="btn primary" href="#keepsakes">Explore Keepsakes <ArrowRight size={17}/></a><a className="textbtn" href="#process">See how it works <ArrowRight size={16}/></a></div><div className="trustline"><ShieldCheck size={18}/>Thoughtfully handled · Made by hand · Created with care</div></div><div className="heroVisual"><div className="heroImage"/><div className="floating"><Heart size={15} fill="currentColor"/>Made for memories that stay.</div></div></section>
  <section className="intro"><div><p className="eyebrow">MORE THAN JEWELLERY</p><h2>A little piece of someone you love, <i>kept forever.</i></h2></div><p>Meaningful materials become beautiful keepsakes. Whether it is ashes, breast milk, fur, hair, flowers or another treasured memory, each piece is handcrafted to hold a story close.</p></section>
  <section id="keepsakes" className="products"><div className="sectionHead"><div><p className="eyebrow">EXPLORE THE COLLECTION</p><h2>Made to mean something.</h2></div><a className="textbtn" href="#contact">Custom keepsakes <ArrowRight size={16}/></a></div><div className="grid">{products.map(([name,type,price,img])=><article className="product" key={name}><div className="productImg"><img src={img} alt=""/><span>KEEPSAKE</span></div><div className="productInfo"><div><p>{type}</p><h3>{name}</h3></div><strong>{price}</strong></div><a href="#contact" className="productLink">Enquire about this piece <ArrowRight size={15}/></a></article>)}</div></section>
  <section className="materials"><div className="materialImage"/><div className="materialCopy"><p className="eyebrow">WHAT CAN BE PRESERVED</p><h2>Made with <i>what matters to you.</i></h2><p>Some memories are too important to leave behind. We create keepsakes incorporating sentimental materials, each handled with the care they deserve.</p><div className="chips"><span>♡ Ashes</span><span>♡ Breast milk</span><span>♡ Hair</span><span>♡ Pet fur</span><span>♡ Flowers</span><span>♡ Other memories</span></div><a className="btn dark" href="#contact">Talk about your keepsake <ArrowRight size={17}/></a></div></section>
  <section id="process" className="process"><div className="centerHead"><p className="eyebrow">THE PROCESS</p><h2>From memory to keepsake, <i>with care.</i></h2><p>We keep the journey simple, personal and reassuring from your first enquiry to the moment your finished piece arrives.</p></div><div className="steps">{[['01','Choose your piece','Explore the collection or tell us what you have in mind.'],['02','Send your material','Receive clear guidance on exactly what to send.'],['03','We craft with care','Your keepsake is made by hand with thoughtful attention.'],['04','Keep the memory close','Your finished piece is carefully prepared and sent to you.']].map(([n,t,d])=><div key={n}><span>{n}</span><Heart/><h3>{t}</h3><p>{d}</p></div>)}</div></section>
  <section className="safety"><div className="safetyCopy"><p className="eyebrow">YOUR MEMORY IS IN SAFE HANDS</p><h2>Because what you send us is <i>irreplaceable.</i></h2><p>We understand that the materials behind a keepsake can carry enormous meaning. Every order deserves patience, privacy and respect.</p><div className="safetyItems"><div><ShieldCheck/><b>Handled respectfully</b><span>Your materials are treated as precious throughout the process.</span></div><div><Heart/><b>Made individually</b><span>Every keepsake receives personal attention and careful finishing.</span></div><div><PackageCheck/><b>Clear guidance</b><span>We make the next step easy to understand before you send anything.</span></div></div></div><div className="safetyCard"><Heart size={27}/><p>KEEPING MEMORIES<br/><strong>CLOSE</strong></p><small>Handcrafted with care</small></div></section>
  <section className="story" id="story"><div className="storyImage"/><div><p className="eyebrow">THE PERSON BEHIND THE KEEPSAKES</p><h2>Created with heart, <i>made for yours.</i></h2><p>Hearts Remembered by M began with a simple belief: the things we hold onto emotionally deserve a beautiful way to stay with us physically.</p><p>Every piece is made with that same thought in mind. Not simply as jewellery, but as a tangible reminder of a person, a chapter, a pet or a moment that will always matter.</p><a className="textbtn" href="#contact">Meet Melissa <ArrowRight size={16}/></a></div></section>
  <section className="quote"><span>“</span><blockquote>It is not just a piece of jewellery. It is something I can carry with me, every single day.</blockquote><p>Customer story · Memorial keepsake</p></section>
  <section id="faq" className="faq"><div className="centerHead"><p className="eyebrow">QUESTIONS, ANSWERED</p><h2>Before you send a <i>single thing.</i></h2></div><div className="faqList">{faqs.map(([q,a],i)=><button key={q} onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><ChevronDown className={open===i?'rot':''}/>{open===i&&<p>{a}</p>}</button>)}</div></section>
  <section id="contact" className="cta"><p className="eyebrow">YOUR MEMORY DESERVES A PLACE TO STAY</p><h2>Ready to create something <i>meaningful?</i></h2><p>Tell us what you would like to preserve and we will guide you from there.</p><a className="btn light" href="mailto:heartsrememberedbym@gmail.com?subject=Keepsake%20Enquiry">Start a conversation <ArrowRight size={17}/></a></section>
  <footer><div><a className="logo lightlogo" href="#top"><span>HEARTS</span><b>remembered</b><small>BY M</small></a><p>Handcrafted keepsakes made from what matters most.</p></div><div className="footerLinks"><div><b>Explore</b><a href="#keepsakes">Keepsakes</a><a href="#process">How It Works</a><a href="#story">Our Story</a></div><div><b>Help</b><a href="#faq">FAQ</a><a href="#contact">Custom Orders</a><a href="mailto:heartsrememberedbym@gmail.com">Contact</a></div></div><div className="copyright">© 2026 Hearts Remembered by M · Demo concept by The Pixel Muses</div></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
